
logging:
  level:
    com.zakmouf: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bluetree
    username: bluetree
    password: mysql
    

spring.mvc.view.prefix: /jsp/
spring.mvc.view.suffix: .jsp

